node:16480) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [ndstr-shard-00-01-zqjw5.azure.mongodb.net:27017] on first connect [MongoError: bad auth Authentication failed.]
    at Pool.<anonymous> (C:\Users\mc038\dev\Teste2\node_modules\mongodb-core\lib\topologies\server.js:431:11)
    at Pool.emit (events.js:198:13)
    at connect (C:\Users\mc038\dev\Teste2\node_modules\mongodb-core\lib\connection\pool.js:557:14)
    at callback (C:\Users\mc038\dev\Teste2\node_modules\mongodb-core\lib\connection\connect.js:109:5)
    at provider.auth.err (C:\Users\mc038\dev\Teste2\node_modules\mongodb-core\lib\connection\connect.js:352:21)
    at _authenticateSingleConnection (C:\Users\mc038\dev\Teste2\node_modules\mongodb-core\lib\auth\auth_provider.js:66:11)
    at sendAuthCommand (C:\Users\mc038\dev\Teste2\node_modules\mongodb-core\lib\auth\scram.js:215:18)
    at Connection.messageHandler (C:\Users\mc038\dev\Teste2\node_modules\mongodb-core\lib\connection\connect.js:334:5)
    at Connection.emit (events.js:198:13)
    at processMessage (C:\Users\mc038\dev\Teste2\node_modules\mongodb-core\lib\connection\connection.js:364:10)
    at TLSSocket.<anonymous> (C:\Users\mc038\dev\Teste2\node_modules\mongodb-core\lib\connection\connection.js:533:15)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
(node:16480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16480) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.